#!/bin/sh -e

# generate key if needed
if [ ! -r $HOME/.ssh/id_dsa.pub ]
then
	echo generate DSA key
	ssh-keygen -t dsa
fi

[ -r $HOME/.ssh/id_dsa.pub ] || { echo missing key; exit 1; }

u=${1%@*}
s=${1#*@}
#echo user=$u server=$s

if [ "$u" ]
then
	if [ ! -r $HOME/.ssh/config ]
	then 
		echo create ssh config file
		touch $HOME/.ssh/config
		chmod 0600 $HOME/.ssh/config
	fi	

	if ! grep "^Host $s" $HOME/.ssh/config > /dev/null
	then
		echo create config entry
		echo "Host $s" >> $HOME/.ssh/config
		echo "	User $u" >> $HOME/.ssh/config
		echo "	Protocol 2" >> $HOME/.ssh/config
		echo >> $HOME/.ssh/config
	fi
fi

cat $HOME/.ssh/id_dsa.pub |\
ssh "$u@$s" "mkdir -p ~/.ssh;chmod 0700 ~/.ssh;cat >> ~/.ssh/authorized_keys;chmod 0600 ~/.ssh/authorized_keys"
