#!/bin/bash

run_time=$2
run_dist_version=$1
ver="5.4.8.1"
path_ver="5_4_8_1"
platform="vox_1.5_pt"
if [ "$2" == "" ]; then
  platform_path_ver=`echo $run_dist_version | sed -e 's%.*platform=\(.*\)&.*%\1%'`
  path_ver=`echo $platform_path_ver | sed -e 's%_[456]_%zzz&%' | sed -e 's%.*zzz_%%'`
  ver=`echo $path_ver | sed -e 's%_%.%g'`
  platform=`echo $platform_path_ver | sed -e 's%_[456]_%zzz&%' | sed -e 's%zzz_.*%%'`
  run_time=`echo $run_dist_version | sed -e 's%.*dir=\(.*\)%\1%'`
else
  if [ "$run_dist_version" != "" ]; then
    path_ver=`echo $run_dist_version | sed -e 's%.*_\([456]_.*\)%\1%'`
    ver=`echo $path_ver | sed -e 's%_%.%g'`
    platform=`echo $run_dist_version | sed -e 's%\(.*\)_[456]_.*%\1%'`
  fi
fi
path=$ver/bat/$run_time

printf "Platform: $platform\n"
printf "Version: $ver\n"
printf "Time: $run_time\n"

cd /tftpboot
mkdir -p $path 2> /dev/null

copy_and_link() {
  cd $path
  if [ "`ls -l $1 2> /dev/null`" == "" ]; then
    wget http://yoda-jungo.cisco.com/arch/rg_qa_autotest/$platform\_$path_ver/$run_time/image/$1.gz 2> /dev/null
    sleep 1;
    if [ "`ls -l $1.gz 2> /dev/null`" != "" ]; then
      gunzip $1.gz
      rt chmod 777 $1
    else
#      wget http://yoda-jungo.cisco.com/arch/rg_qa_autotest/$platform\_fast_$path_ver/$run_time/image/$1.gz 2> /dev/null
#      sleep 1;
#      if [ "`ls -l $1.gz 2> /dev/null`" != "" ]; then
#	gunzip $1.gz
#	rt chmod 777 $1
#      else
	return 1
#      fi
    fi
  fi
  cd /tftpboot
  unlink $1
  ln -sf $path/$1
  ls --color=auto -la $1

  return 0
}

copy_and_link openrg &
copy_and_link openrg.img &
copy_and_link openrg.rmt &
copy_and_link openrg.rms &
copy_and_link rgloader.img &
copy_and_link rg_factory &
copy_and_link image.elf &
copy_and_link flash.img &
copy_and_link ubi.img 

if [ "`ls -l /tftpboot/$path/openrg.rmt 2> /dev/null`" != "" ]; then
  rt unlink /var/www/openrg.rmt 
  rt ln -sf /tftpboot/$path/openrg.rmt /var/www/openrg.rmt
  ls --color=auto -la /var/www/openrg.rmt
fi
if [ "`ls -l /tftpboot/$path/openrg.rms 2> /dev/null`" != "" ]; then
  rt unlink /var/www/openrg.rms 
  rt ln -sf /tftpboot/$path/openrg.rms /var/www/openrg.rms
  ls --color=auto -la /var/www/openrg.rms
fi
