#!/bin/sh
#
# Wrapper around make, to colorize it's output and pipe through less.
# Jumps to the first gcc error that occurs during the build process.
#

time /usr/bin/make $* 2>&1 | ~/my/scripts/colormake.pl -1
#time nice -18 ionice -c 3 /usr/bin/make $* 2>&1 | ~/my/scripts/colormake.pl -1
#time /usr/bin/make $* 2>&1 
x=$PIPESTATUS
if (($x)); then
  rt beep -f800 -l120 -n -f700 -l150 -n -f500 -l180 -n -f300
else
  rt beep -f1000 -l120 -n -f1400 -l120 -n -f1200 -l120 -n -f1600 -l120 -n -f1800
  #xmessage -center -default okay make in `pwd` succeeded at `date` &
fi
exit $x
#make $* 2>&1 | colormake.pl
