#!/bin/sh

# In order to install, run: git config --global  diff.external git_diff

# diff is called by git with 7 parameters:
# path old-file old-hex old-mode new-file new-hex new-mode

"xxdiff" "$2" "$5"
exit 0
