#!/bin/bash

C_RED='\033[1;31m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_BLUE='\033[1;34m'
C_PURPLE='\033[1;35m'
C_CYAN='\033[1;36m'
C_WHITE='\033[1;37m'
C_BLACK='\033[1;38m'
C_DEF='\033[0m'

cd

for tree in `ls -d /mnt/sdb2/home/royi/*.rg`; do
    #if [ -L $tree/Makefile ]; then
    #  TAG="`file $tree/Makefile | sed -e 's%.*/\(rg.[^/]*\).*%\1%'`"
    #  TAG="»»$TAG"
    #else
      TAG=`cvs stat $tree/Makefile | grep Tag | sed -e 's/(none)/dev ()/' | sed -e 's/ *Sticky Tag:[^b(]\(.*\) (.*/\1/'`
    #fi
    #    TIME=`grep RG_COMPILE_TIME $tree/pkg/include/tech_info.h | sed -e 's%.*"[^ ]* \(.*\)".*%\1%'`

    printf "$C_BLUE%-11s$C_PURPLE%-18s$C_DEF%-24s\n" $tree $TAG "$TIME"
    modified=`cat $tree/list 2> /dev/null`
    if [ "$modified" != "" ]; then
        printf "$modified\n"
    fi

    for conf in `ls $tree/build.*/config 2> /dev/null`; do
        if [ ! -L `dirname $conf` ]; then
	    CONF=`cat $conf | sed -e 's/DIST=//'`
	    failed=`cat $tree/failed 2> /dev/null | grep $CONF`
	    ctime=`cat $tree/compile_date 2> /dev/null | grep -w $CONF |  sed -e 's/'$CONF'//'`
	    if [ "$failed" != "" ]; then
		printf "\t\t$C_RED%-20s\t$C_DEF%-2s\n" $failed "$ctime" 
	    else
	        printf "\t\t$C_GREEN%-20s\t$C_DEF%-2s\n" $CONF "$ctime"
	    fi
	fi
    done

    
done

