#!/bin/sh

# silent cake (silent in sound)
# silent cake (silent in sound, printouts are as usual)

#make $* 2>&1 
time make $* 2>&1 | ~/my/scripts/colormake.pl -1
#time nice -18 ionice -c 3 make $* 2>&1 | ~/my/scripts/colormake.pl -1
exit $PIPESTATUS
