#!/bin/bash

for rev in $(cat all_revs) ; do
  ver=`echo $rev |  sed 's/R[0-9][0-9][0-9]\(.*\)/\1/g'`
  num=`cat ~/review/$ver/$rev | grep -c -w branch-4_10_4_2_7_1`
  if [ $num -gt 1 ]; then
    printf "$rev has $num\n"
  fi
done
